function varargout = capturerun( script__ , varargin)

run(script__);

if nargin <= 1
% return 

vars = setdiff(who,{'script__','varargin'});	
for k = 1:length(vars)
		% Add to struct
		out.(vars{k}) = eval(vars{k});
		
		% Clear variable if requested
		clear(vars{k} );
end	
varargout{1} = out;
else

avail_vars = setdiff(who,{'script__','varargin'});	
	
for var_idx = 1:length(varargin)
	
	if~ismember( varargin{var_idx}, avail_vars )
		error('Variable "%s" not generated by %s', varargin{var_idx}, script__);
	end
		
	varargout{var_idx} = eval( varargin{var_idx});
	
end

end
	
end

